### ISSUE TITLE
Key len check always false?

### ISSUE THREAD

**Issue by mcsherrylabs** [filip26/iron-ed25519-cryptosuite-2020#20]
https://github.com/filip26/iron-ed25519-cryptosuite-2020/blob/24c391f98f854deb29d256b01e5110d6000ed152/src/main/java/com/apicatalog/ld/signature/ed25519/Ed25519Signature2020.java#LL45C43-L45C43

Looks like you're checking the key length against 3 different values, should be || instead of && ?

**Comment by filip26** [comment]
Hi, thank you for reporting that, looks like a bug. The suite has been refactored, please see https://github.com/filip26/iron-ed25519-cryptosuite-2020/blob/6ec5281205c33922e341fb9e578b9d4dd310f7b3/src/main/java/com/apicatalog/ld/signature/ed25519/Ed25519Signature2020Proof.java#L35
